[package]
name = "crabcan"
version = "0.1.0"
edition = "2021"

[dependencies]
capctl = "0.2.0"
env_logger = "0.11.5"
log = "0.4.22"
nix = "0.22.1"
rand = "0.8.5"
scan_fmt = "0.2.6"
structopt = "0.3.26"
syscallz = "0.16.1"
libc = "0.2.102"
cgroups-rs = "0.2.6"
rlimit = "0.6.2"